### ISSUE TITLE
Please say in the README it doesn't handle other gamemodes

### ISSUE THREAD

**Issue by Adrriii** [kszlim/osu-replay-parser#16]
```    
def parse_play_data(self, replay_data):
        if self.game_mode != GameMode.Standard:
            self.play_data = None
```

Had to dig in the program to find out why it wouldn't work on mania replays

**Comment by blimmo** [comment]
Note this is only what [the wiki](https://osu.ppy.sh/help/wiki/osu%21_File_Formats%2FOsr_%28file_format%29) calls "replay data" and the code calls `play_data` which is the compressed stream of mouse movements. Everything else (e.g. number of 300s, player name, md5) should be fine.

I can't imagine this makes much sense on gamemodes other than standard so I expect there isn't actually any of this part of the data there for them.

I didn't write the code and I only really deal with standard myself so I can't say I actually know whether there is some data here (perhaps on mania it has a sequence of keypresses and the time between them?).

**Comment by Adrriii** [comment]
It is in fact relevant for other gamemodes, it just has to be interpreted another way :)

For mania, whenever an release/input event is triggered you get the time since last event and a bitwise representation of the keys (like 0011 if you press the two keys on the left in 4k)

Anyway ; I ended up using another tool because all i needed was to separate the play data from the rest as I had already done a script to decompress and read the replay :)

Thank you for the tool anyway it looks very good :)

**Comment by blimmo** [comment]
Oh cool!

I probably won't be adding support for that but if you ever feel like sharing (either code to parse it or just how it works so someone else can actually write the code) then feel free to make a PR (I don't blame you if you don't tho I can never find the time to commit anything meaningful).

(might be better to PR [slider](https://github.com/llllllllll/slider) instead if you want to: I think it's more active / complete)

Or consider adding the info to the wiki, honestly that needs more love it makes no mention of non-standard gamemodes in the replay_data section.

But yeah the README probably should mention the lack of support for that. @kszlim?

**Comment by Adrriii** [comment]
Oh i'm really not into python (more Java and PHP), so I prefer not to ^^ Also, parsing this format is a mess and I wouldn't give it another try even though I already did it in php ahah

**Comment by kszlim** [comment]
I should really try to maintain this better. Maybe I'll investigate the effort needed to support other game modes.

**Comment by tybug** [comment]
closed by https://github.com/kszlim/osu-replay-parser/pull/28, which enables parsing all gamemodes
