### ISSUE TITLE
parse_string

### ISSUE THREAD

**Issue by abraker95** [kszlim/osu-replay-parser#17]
It is not returning anything if it's a regular string

**Comment by abraker95** [comment]
The fix
```
if replay_data[self.offset] == 0x00:
    self.offset += Replay.__BYTE
    begin = self.offset
    while replay_data[self.offset] != 0x00: 
        self.offset += Replay.__BYTE
    return replay_data[begin:self.offset-1].decode("utf-8")
```

**Comment by kszlim** [comment]
Please submit a PR, and I'll get it merged in!

**Comment by tybug** [comment]
I'm going to be honest, I can't understand what the issue here is. I don't see any way our current usage of `parse_string` is causing errors, and I'm not sure what a "regular string" is. 

`parse_string` (now `_parse_string`) is an internal method and shouldn't be used by consumers, if I'm correct in assuming that's what's going on here.

**Comment by abraker95** [comment]
> and I'm not sure what a "regular string" is.

I called a null terminated string a "regular string" to indicate that it's not an LMZA encoded string. 

---

It's been a while since I have looked at this, so details of what happened are hazy. I've come across replay files that are corrupt for various reasons like blank lifebar data or missing game version number. I don't remember whether these replays came from  the osu! client, web, or the osu!api, but I included an example of one below. 

For all intents and purposes, these replays were indeed corrupt and could not be loaded by osu!. It did not happen randomly, meaning that the replays were actually like that. It was quite annoying in my data collection process to come across such replays, so I looked into ways to read the data anyway despite the corrupted state. 

I hacked together a solution which worked for a while until I came another instance of a replay which did not work due to something in `parse_string`. By that time I forgot about the changes I've done and legitimately thought this was a bug in the library. So I am not sure this is relevant anymore, or even valid for that matter.

According to some code [comments I made from a couple years back](https://i.imgur.com/pItWuOI.png), this is an example replay with no game version number, but otherwise readable:
[LeaF - I (Maddy) [Terror].zip](https://github.com/kszlim/osu-replay-parser/files/6566754/LeaF.-.I.Maddy.Terror.zip)

**Comment by tybug** [comment]
Thanks for the explanation. Very weird...if even osu! can't load these replays then I think it's safe to chalk this up to "not our problem" and call it a day.

If there were a lot of these replays or we knew they were coming from somewhere official (eg, maybe the osu! client generated corrupted replays at some point), it might be worth including a fix in this library, but until then, I don't think it's our place to do so.

**Comment by tybug** [comment]
going to close per above, at least until an officially downloadable replay with this deficiency is found, at which point I'd be happy to reconsider 'fixing' this at the library level
