### ISSUE TITLE
Can't parse replays with ScoreV2 mod

### ISSUE THREAD

**Issue by abraker95** [kszlim/osu-replay-parser#18]

**Comment by kszlim** [comment]
I'm not actively maintaining this anymore, but I'll accept PRs. Otherwise, I might get to it, but very slowly.

**Comment by tybug** [comment]
For the record, we're maintaining a downstream fork at https://github.com/circleguard/circleparse (and have been for a while). Maybe someone will find it useful in the future. Incidentally, thanks for your work on this library!

**Comment by kszlim** [comment]
Haha, thanks, never thought it would get the level of use it has seen.

**Comment by jxu** [comment]
btw circleguard switched to using https://github.com/llllllllll/slider

**Comment by tybug** [comment]
not for replays - we're still using circleparse for that
