### ISSUE TITLE
osu!mania replay_data all 0s

### ISSUE THREAD

**Issue by Eve-ning** [kszlim/osu-replay-parser#35]
Version `6.0.0`

All read events of an `osu!mania` replay is 0

```py
>>> rep = Replay.from_path(...)
>>> all([d.keys == 0 for d in rep.replay_data])
True
```

**Comment by Eve-ning** [comment]
[#MAGiCVLGiRL_TRVP_B3VTZ [ZVPH'Z_ACC].zip](https://github.com/kszlim/osu-replay-parser/files/9060232/MAGiCVLGiRL_TRVP_B3VTZ.ZVPH.Z_ACC.zip)

Test cases above

**Comment by tybug** [comment]
whoops, stupid mistake on my part. should be fixed by https://github.com/kszlim/osu-replay-parser/commit/121b261d7b6491154ab6bcf72960de2a241eed36

**Comment by Eve-ning** [comment]
yeap, seems to work now 👍

**Comment by tybug** [comment]
no problem :) I've release v6.0.1 with this fix.
