### ISSUE TITLE
Parser reads unsigned value as signed

### ISSUE THREAD

**Issue by OlegSuperBro** [kszlim/osu-replay-parser#42]
All values in replay is written as unsigned values, but parser reads them as unsigned, that leads reading values bigger than 32767 as negative numbers

**Comment by tybug** [comment]
wow, I don't know how that went unnoticed for so long. Thanks for the report.

**Comment by OlegSuperBro** [comment]
Just small thing, only score saved as signed value

**Comment by tybug** [comment]
fixed in https://github.com/kszlim/osu-replay-parser/commit/56ca1323a5d403ac9f3c5349ae224e9fd030bda2, thanks for your patience.
